### ISSUE TITLE
Error "file not found: /software/R-2.15.2/bin/R" when running with sample script and data

### ISSUE THREAD

**Issue by mullinyu** [findingdan/UPDio#2]
My linux is installed with R version 3.5.1 (2018-07-02)

But, I got the following error when running with ./run_UPDio_example.sh
file not found: /software/R-2.15.2/bin/R at /home/appuser/lib/perl5/site_perl/5.22.0/Statistics/R.pm line 356.

But, I can't find any hardcoded R-2.15.2 in R.pm file.

from output_dir, I can only see
child.exome.sorted.homREFed.events_list (2054KB)
child.exome.sorted.homREFed.log (1KB)
child.exome.sorted.homREFed.table (2KB)
child.exome.sorted.homREFed.upd (0 KB)

Any idea?

**Comment by mullinyu** [comment]
Fixed as their hardcoded path in pl file.

**Comment by Daverbuj-Genomics** [comment]
> 

Mullinyu, would you happen to recall what change you made to the pl file?

**Comment by francois-lecoquierre** [comment]
Hi, I'm having the same error message :
file not found: /software/R-2.15.2/bin/R at /usr/local/share/perl/5.30.0/Statistics/R.pm line 356
I am using Statistics::R version 0.34 as I can't install version 0.31. 0.34 seems to be the same version as @mullinyu as the error is at the same line.
Do you have any ideas ?

**Comment by francois-lecoquierre** [comment]
Ok got it too, the problem is in the UPDio.pl line 35, the "path_to_R" that pointed to another version of R
